//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TTNN1_QLBachHoa
{
    using System;
    using System.Collections.Generic;
    
    public partial class CHI_TIET_PHIEU_NHAP
    {
        public long MaCTPN { get; set; }
        public string MaPN { get; set; }
        public string MaSP { get; set; }
        public int SoLuongNhap { get; set; }
        public decimal DonGiaNhap { get; set; }
        public decimal ThanhTienNhap { get; set; }
    
        public virtual PHIEU_NHAP_KHO PHIEU_NHAP_KHO { get; set; }
        public virtual SAN_PHAM SAN_PHAM { get; set; }
    }
}
