//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TTNN1_QLBachHoa
{
    using System;
    using System.Collections.Generic;
    
    public partial class PHIEU_NHAP_KHO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PHIEU_NHAP_KHO()
        {
            this.CHI_TIET_PHIEU_NHAP = new HashSet<CHI_TIET_PHIEU_NHAP>();
        }
    
        public string MaPN { get; set; }
        public string MaNCC { get; set; }
        public string MaNV { get; set; }
        public Nullable<System.DateTime> NgayNhap { get; set; }
        public decimal TongTienNhap { get; set; }
        public string GhiChu { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CHI_TIET_PHIEU_NHAP> CHI_TIET_PHIEU_NHAP { get; set; }
        public virtual NHA_CUNG_CAP NHA_CUNG_CAP { get; set; }
        public virtual NHAN_VIEN NHAN_VIEN { get; set; }
    }
}
